[package]
name = "aquila-kernel"
version = "0.1.0"
authors = ["Mohamed Hamza <manwar@aquilaos.com>"]

[lib]
name = "kernel"
crate-type = ["staticlib"]

[build-dependencies]
cc = "1.0"
cargo-post = "0.1.1"
